# Generated by Django 4.2.27 on 2026-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='emi_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='emi_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_per_couple',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_per_group',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
